### ISSUE TITLE
C4Worshops

### ISSUE THREAD

**Issue by SALAH-EDDIB** [SALAH-EDDIB/javaScript#2]
- [x] Enoncé 1

- [x] Enoncé 2

- [x] Enoncé 3

- [x] Enoncé 4

- [x] Enoncé 5 

- [x]  Enoncé 6

- [x]  Enoncé 7

**Comment by youssefbm** [comment]
Hey Salah, I will be assigning to you the live coding of the 7th exercice. So I invite you to checkout how to replace loops with recursions.

**Comment by youssefbm** [comment]
I need every solution in its own js file.

**Comment by youssefbm** [comment]
Exercice 3 and Exercice 1

**Comment by SALAH-EDDIB** [comment]
in the js folder, you gonna find ennonce1 et ennonce3 js files

**Comment by youssefbm** [comment]
Exercice 3: arr.shif() should be returned

**Comment by SALAH-EDDIB** [comment]
first I log in the console the first num in the array by [
console.log('deleted item  :' + arr[0])
]

 and i  deleted by [
arr.shift()
]


or I can use [ return arr.shift(); ]
